version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/tmp
    networks:
      - mono-pnpm-temple-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - mono-pnpm-temple-network

  consul:
    image: consul:latest
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - mono-pnpm-temple-network

networks:
  mono-pnpm-temple-network:
    external: true