version: "3.9"

services:
  api-gateway:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-1}
      cache_from:
        - "mono-pnpm-temple-registry:5000/api-gateway:${CACHE_FROM:-local}"
        - "mono-pnpm-temple-registry:5000/api-gateway:master-latest"
    image: mono-pnpm-temple-registry:5000/api-gateway:${VERSION:-local}
    container_name: api-gateway
    ports:
      - 8080:8080
    networks:
      - mono-pnpm-temple-network

networks:
  mono-pnpm-temple-network:
    external: true