const LOG_IDENTIFIER_LOG_FIELD = 'logIdentifier';
export const LogIdentifiers = {
  ERROR_UNHANDLED_REJECTION: 'ERROR_UNHANDLED_REJECTION',
  ERROR_UNCAUGHT_EXCEPTION: 'ERROR_UNCAUGHT_EXCEPTION',
  ERROR_HANDLED_ROUTE_ERROR: 'ERROR_HANDLED_ROUTE_ERROR',
  UNAUTHORIZED_IP_ACCESS: 'UNAUTHORIZED_IP_ACCESS',
  UNAUTHORIZED_DOMAIN_ACCESS: 'UNAUTHORIZED_DOMAIN_ACCESS',
  RESPONSE_FROM_ELASTICSEARCH: 'RESPONSE_FROM_ELASTICSEARCH',
  ERROR_LOGIN_AUTH0: 'ERROR_LOGIN_AUTH0',
  ERROR_LOGIN_JWT: 'ERROR_LOGIN_JWT',
  DOMAIN_NOT_AUTHORIZED: 'DOMAIN_NOT_AUTHORIZED',
  ERROR_LOGIN_AUTH0_POST: 'ERROR_LOGIN_AUTH0_POST',
  ERROR_FOUND_XSS_SIGNUP: 'ERROR_FOUND_XSS_SIGNUP',
  ERROR_FETCHING_CONFIG: 'ERROR_FETCHING_CONFIG',
  STOPPING_SERVER: 'STOPPING_SERVER',
  SEND_YOUR_DATA_ERROR: 'SEND_YOUR_DATA_ERROR',
  ACCESS_LOG: 'ACCESS_LOG',
};

export function addLogIdentifier(identifier = null, data = {}) {
  data[LOG_IDENTIFIER_LOG_FIELD] = identifier;

  return data;
}
